### ISSUE TITLE
Doesn't run on Linux?

### ISSUE THREAD

**Issue by lucasmr** [poiuyqwert/PyMS#110]
Running Gentoo, Python 2.7.15 with Pillow 5.2.0.

$ ./setup.py 
import: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.
./setup.py: line 2: $'\r': command not found
./setup.py: line 3: progs: command not found
./setup.py: line 5: syntax error near unexpected token `progs.append'
./setup.py: line 5: `	progs.append({"script":prog + ".pyw","icon_resources": [(1, "Images\\%s.ico" % prog)]}'

running with python:
$ python2 setup.py 
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    ('Libs\\Data',list('Libs\\Data')),
  File "setup.py", line 8, in list
    return [os.path.join(path,file) for file in os.listdir(path) if not file in exc]
OSError: [Errno 2] No such file or directory: 'Libs\\Data'

**Comment by poiuyqwert** [comment]
Hey @lucasmr,

The `setup.py` file has confused people before, it is a very poorly named script. I previously used it with py2exe to generate releases of PyMS wrapped up as .exe files for windows users (I no longer do windows releases).

If you wan't to run one of the programs, for instance `PyDAT`, you can just run the main scripts like `python2 PyDAT.pyw`

I hope that helps!
