### ISSUE TITLE
PIL is still missing

### ISSUE THREAD

**Issue by walt253** [poiuyqwert/PyMS#143]
![image](https://github.com/poiuyqwert/PyMS/assets/130906143/7601043b-24fa-40a1-a017-0ec4934126c6)

I'm doing something wrong?

**Comment by walt253** [comment]
![image](https://github.com/poiuyqwert/PyMS/assets/130906143/e083a593-2ba6-4e74-a7ed-408420b48e2c)

**Comment by walt253** [comment]
I gave up. Sorry for the inconvenience.

**Comment by KYSXD** [comment]
Just tu be sure, are you running with python 2.7?

try running
```bash
$ python2.7 -m pip install -r requirements.tx
```

as said in the requirements file
